site_name: ee-france

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
